##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES
#
# url is your gh-pages base, following the pattern: username.github.io
url: 
# baseurl is your github repository's name prefixed with a /
baseurl: 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: MBMG Data Preservation Documentation
# tagline, a short phrase that will appear throughout the site in the top banner
tagline:
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "In 1919, the Montana Legislature created the Montana Bureau of Mines and Geology (MBMG or Bureau). The Bureau’s mission is to collect, maintain, manage, and preserve information having enduring historic, research, and informational value, make the information available to the public, and dispose information whose enduring value has expired.

The Montana Bureau of Mines and Geology collects geologic and mineral, specimens, geologic, hydrologic, seismic, and mining-related historical photographs, reports, and analysis pertaining to the State of Montana.

MBMG created a data preservation program and Archives department that assesses, acquires, organizes, restores, and preserves historic mining, geologic, hydrogeologic, mineral, and seismic information pertaining to the state of Montana. The MBMG Data Preservation Program makes this information available to the public, in both physical and electronic formats for education and research purposes."
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Chelsea Pincock

##########
# COLLECTION SETTINGS
#
# choose metadata: this is the name of the csv file in your _data directory that describes the objects in your collection
metadata: demo-metadata 

##########
# GOOGLE SERVICES [optional!]
#
# leave these blank or comment out to NOT include google code. See docs/google.md
#
# Add your google-analytics-id to automatically add the embed code, e.g. "UA-76328753-1"
# google-analytics-id:
# to populate a Google CSE add the id, e.g. "002151703305773322890:1pu3smhw1t8"
# google-cse-id: 

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: true 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE]
# compress CSS output
sass:
  style: compressed
